FROM logstash:7.0.1

RUN logstash-plugin install logstash-filter-json
RUN logstash-plugin install logstash-filter-i18n
RUN logstash-plugin install logstash-filter-json_encode
RUN logstash-plugin install logstash-filter-geoip
